### PR TITLE
Add options support to the DomPdf engine.

### PR DESCRIPTION
**Pull request by ndm2**
Recently CakePdf switched to [supporting the new 0.7 branch of DomPdf](https://github.com/FriendsOfCake/CakePdf/commit/d50c0e7a83e8db567384c24dae0437741bd5a8f2), which not only uses namespaces, but also changed quite a few internals, one being that pretty much all the options constants are gone, and the `DomPdf` class now needs to be explicitly fed with options.

The new branch is still in beta, so I'm not sure whether CakePdf should jump on supporting/requiring it yet, but if it should, then it would be good if it would support options, which this PR aims to implement.

Currently there seems to be no option for the orientation, so for now page size and orientation is still set via `DomPdf::setPaper()`. There's probobaly going to be some change around this, see https://github.com/dompdf/dompdf/blob/v0.7.0-beta3/src/Dompdf.php#L740, so one should keep an eye on that.

ps. I can add tests later on in case this PR is being considered to be merged.

### CODE REVIEW

**Comment by ADmad** [comment]
There were at least a couple of issues regarding dompdf not being loaded and the proposed fix was to add the namespace. Only after making the suggested change and making a release did i release that the change would now require using dompdf 0.7 which was still in beta.

But I chose not to revert the change since I saw that the readme of dompdf's master branch itself suggests installing 0.7-beta and hence that's what most people were doing.

So I am fine with any changes required to support dompdf 0.7.

**Comment by ndm2** [comment]
I see, that's fair enough. I've done some further restructuring and added a few tests.

**Comment by ADmad** [comment]
Let me know when it's ready to go :)

I think i'll revert the namespace change on master and make a new release. Then after merging your changes will bump the minor version of plugin.

**Comment by ndm2** [comment]
Moving things to a new minor sounds reasonable.

I think it's good to go, coverage for the engine looks fine, for now that's good enough for me :)

**Comment by ADmad** [comment]
Please rebase :)

**Comment by ndm2** [comment]
Done so...

**Comment by ADmad** [comment]
Can you please also update the composer require command for dompdf in readme to specify 0.7

**Comment by ndm2** [comment]
Sure thing... should it maybe also include a note that it should be changed once 0.7 becomes stable?

**Comment by ADmad** [comment]
Sounds good.

**Comment by ndm2** [comment]
Done diddly done

**Comment by ADmad** [comment]
Thanks @ndm2. I have release 3.2.0

**Pull request merged**
