### PR TITLE
Use TCPDF engine through Composer

### PR DESCRIPTION
**Pull request by ravage84**

### CODE REVIEW

**Comment by dakota** [comment]
This doesn't break BC? And we should probably do the same treatment for the other supported engines.

I'll be able to look in depth once I'm back home.

**Comment by dereuromark** [comment]
Isn't that part of what the develop branch currently already consists of? https://github.com/FriendsOfCake/CakePdf/tree/develop

We should get that merged at some point.

**Comment by dakota** [comment]
Indeed

CakePDF does need some serious love. I will be taking a more active approach in maintaining it in the future.

**Comment by ravage84** [comment]
:imp: That's why I dislike develop branches. Especially if they aren't documented... 

@dakota probably it's not BC right now. I assume it would take an approach like this:
https://github.com/FriendsOfCake/CakePdf/blob/82750dd13574a084daeff21fc76fabf40352bfeb/Pdf/Engine/DomPdfEngine.php#L21-L24

But this would mean we still need to keep the totally outdated TCPDF files.
I personally think it's not the BC responsibility of this library to contain outdated third party libraries just to garantuee BC. Certainly I would not do this change in a patch release, though :smirk_cat:

**Comment by ceeram** [comment]
Ill pick up maintainment soon once business is all sorted. Other priorities
atm, but it wont be abandoned by me.
Op 2 jun. 2015 12:37 schreef "Marc Würth" <notifications@github.com>:

**Comment by ADmad** [comment]
This has been taken care of.

**Pull request closed without merging**
