### PR TITLE
Add license badge

### PR DESCRIPTION
**Pull request by dereuromark**
Simplify Readme

maybe one of the repo owners can adjust the heading:

```
 CakePHP plugin for creating and/or rendering Pdf, several Pdf engines supported
```

to

```
CakePHP plugin for creating and/or rendering PDFs, supporting several popular PDF engines.
```

### CODE REVIEW

**Comment by dereuromark** [comment]
@dakota Doesn't look like he heard us :)

**Comment by dakota** [comment]
Maybe I need to say his name three times. @ceeram @ceeram @ceeram :smile:

**Comment by ceeram** [comment]
Hi :) will update the description

2015-01-13 7:32 GMT+01:00 Walther Lalk <notifications@github.com>:

**Comment by ceeram** [comment]
Just why was the license and copyrights removed? people downloading the package, dont have the icon in the text version of the readme, also copyrights shouldnt be removed

**Comment by dakota** [comment]
I didn't even notice that when I merged. Sorry @ceeram, I've restored the license in a `LICENSE` file.

**Comment by dereuromark** [comment]
Sry, I was actually submitting a LICENSE.txt file similar to the other repos here, but that got not commited then by accident. My bad.

**Pull request merged**
